---
- name: squid
  hosts: '{{ target }}'
  vars:
  become: True
  become_user: root
  tasks:
    - name: epel package
      yum:
        name: epel-release
        state: latest

    - name: squid package
      yum:
        name: squid
        state: latest

    - name: squid service enabled/started
      systemd:
        name: squid
        state: started
        enabled: yes

    - name: squid.conf read-only (managed via squid-allowed-hosts)
      copy:
        src: conf/squid.conf
        dest: /etc/squid/squid.conf
        owner: root
        group: squid
        mode: 440
        backup: yes
      register: squid_conf

    - name: squid service restarted on conf change
      systemd:
        name: squid
        state: restarted
      when: squid_conf.changed
